### ISSUE TITLE
Rethinkdb on arm64/v8 architecture

### ISSUE THREAD

**Issue by jackbrimble2** [lewjc/CombiLog#21]
Hi Lewis,
I've been building the combilog stack on an arm device. It was just a case of creating a new image on the device to allow the combilog containers to run, however the rethinkdb container doesn't have an arm image so doesn't run. I found an [alternative](https://github.com/gounthar/docker-rethinkdb) that is built for the arm architecture but returns this after running `docker-compose up`:

```
Creating compose_rethinkdb_1 ... done
Creating compose_aggregator_1 ... done
Creating compose_dashboard_1  ... done
Creating compose_archiver_1   ... done
Attaching to compose_rethinkdb_1, compose_aggregator_1, compose_dashboard_1, compose_archiver_1
aggregator_1  | 2021-11-22T14:39:37: PM2 log: Launching in no daemon mode
aggregator_1  | 2021-11-22T14:39:37: PM2 log: App [server:0] starting in -fork mode-
aggregator_1  | 2021-11-22T14:39:37: PM2 log: App [server:0] online
aggregator_1  | BEGINNING DATABASE SCHEMA CHECK
rethinkdb_1   | Error in the command line: Unexpected positional parameter 'rethinkdb' (did you forget the option name, or forget to quote a parameter list?).
rethinkdb_1   | Run 'rethinkdb help' for help on the command
compose_rethinkdb_1 exited with code 1
dashboard_1   | 2021/11/22 14:39:38 [notice] 1#1: using the "epoll" event method
dashboard_1   | 2021/11/22 14:39:38 [notice] 1#1: nginx/1.21.4
dashboard_1   | 2021/11/22 14:39:38 [notice] 1#1: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424) 
dashboard_1   | 2021/11/22 14:39:38 [notice] 1#1: OS: Linux 4.9.140-tegra
dashboard_1   | 2021/11/22 14:39:38 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
dashboard_1   | 2021/11/22 14:39:38 [notice] 1#1: start worker processes
dashboard_1   | 2021/11/22 14:39:38 [notice] 1#1: start worker process 9
dashboard_1   | 2021/11/22 14:39:38 [notice] 1#1: start worker process 10
aggregator_1  | Error: getaddrinfo EAI_AGAIN rethinkdb
aggregator_1  | Error: getaddrinfo EAI_AGAIN rethinkdb
aggregator_1  | Error: getaddrinfo EAI_AGAIN rethinkdb
aggregator_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
aggregator_1  |   errno: 'EAI_AGAIN',
aggregator_1  |   code: 'EAI_AGAIN',
aggregator_1  |   syscall: 'getaddrinfo',
aggregator_1  |   hostname: 'rethinkdb'
aggregator_1  | }
archiver_1    | 2021-11-22T14:39:39: PM2 log: Launching in no daemon mode
archiver_1    | 2021-11-22T14:39:39: PM2 log: App [index:0] starting in -fork mode-
archiver_1    | 2021-11-22T14:39:39: PM2 log: App [index:0] online
aggregator_1  | 2021-11-22T14:39:40: PM2 log: App [server:0] exited with code [0] via signal [SIGINT]
aggregator_1  | 2021-11-22T14:39:40: PM2 log: App [server:0] starting in -fork mode-
aggregator_1  | 2021-11-22T14:39:40: PM2 log: App [server:0] online
archiver_1    | Listening on port 13338
archiver_1    | {
archiver_1    |   rss: 56479744,
archiver_1    |   heapTotal: 29609984,
archiver_1    |   heapUsed: 15940888,
archiver_1    |   external: 2030319,
archiver_1    |   arrayBuffers: 508930
archiver_1    | }
archiver_1    | Connection to aggregator failed. ERROR: Error: connect ECONNREFUSED 172.21.0.3:13337
archiver_1    | Connection to aggregator closed. CODE 1006. REASON  Reconnection attempt will occur in 5 seconds...
```

The archiver/aggregator errors loop forever after that.

The compose file if you need it: 

```
version: "3.8"
services:
  dashboard:
    image: combilog-dashboard:arm64
    volumes:
      - combilog-dashboard:/usr/share/nginx/html/config/
    ports:
      - "4322:80"
    depends_on: [aggregator]
    env_file:
      - dashboard.env
  archiver:
    image: combilog-archiver:arm64
    volumes:
      - combilog-archive:/usr/src/app/data
    ports:
      - "13338:13338"
    env_file:
      - archive.env
    depends_on: [aggregator]
  aggregator:
    image: combilog-aggregator:arm64
    ports:
      - "13337:13337"
      - "3000:3000"
    depends_on: [rethinkdb]
    env_file:
      - aggregator.env
  rethinkdb:
    image: gounthar/docker-rethinkdb:latest
    volumes:
      - combilog-db:/data
    ports:
      - "4321:8080"
      - "28015:28015"
    command: rethinkdb -d /data --bind all

volumes:
  combilog-db:
  combilog-dashboard:
  combilog-archive:
```

Any assistance on this problem would be appreciated, if you need any other info let me know. Thanks very much
